name: buildkit
services:
  buildkit:
    container_name: buildkit-dev
    build:
      context: ../..
      args:
        BUILDKIT_DEBUG: 1
    image: moby/buildkit:local
    ports:
      - 127.0.0.1:1234:1234
      - 127.0.0.1:5000:5000
      - 127.0.0.1:6060:6060
    restart: always
    privileged: true
    environment:
      DELVE_PORT: 5000
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
    configs:
      - source: buildkit_config
        target: /etc/buildkit/buildkitd.toml
    volumes:
      - buildkit:/var/lib/buildkit

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 127.0.0.1:16686:16686

volumes:
  buildkit:

configs:
  buildkit_config:
    file: ./buildkitd.toml
